{{- if .Values.bridges.signal.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix.fullname" . }}-signal-config
  labels:
  {{ include "matrix.labels" . | nindent 4}}
data:
  config.yaml: |
  {{ include "matrix.irc.config" . | nindent 4 }}
{{- end }}
