{{- if .Values.bridges.signal.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matrix.fullname" . }}-bridge-signal
  labels:
{{ include "matrix.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.bridges.signal.replicaCount }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "matrix.name" . }}-bridge-signal
      app.kubernetes.io/instance: {{ .Release.Name }}
      matrix-chart/allow-synapse-access: allow
  template:
    metadata:
      annotations:
        # re-roll deployment on config change
        checksum/signal-config: {{ include (print $.Template.BasePath "/bridge-signal/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "matrix.name" . }}-bridge-signal
        app.kubernetes.io/instance: {{ .Release.Name }}
        matrix-chart/allow-synapse-access: allow
    spec:
      {{- if .Values.bridges.affinity }}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "matrix.name" . }}-synapse
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - {{ .Release.Name }}
              topologyKey: kubernetes.io/hostname
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: "load-config"
          image: "{{ .Values.bridges.signal.image.repository }}:{{ .Values.bridges.signal.image.tag }}"
          imagePullPolicy: {{ .Values.bridges.signal.image.pullPolicy }}
          command: ["sh"]
          args: ["-c", "cp /load/config.yaml /data/config.yaml"]
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /load
              readOnly: true
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
        - name: "generate-config"
          image: "{{ .Values.bridges.signal.image.repository }}:{{ .Values.bridges.signal.image.tag }}"
          imagePullPolicy: {{ .Values.bridges.signal.image.pullPolicy }}
          command: ["mautrix-signal"]
          args: ["-g", "-c", "/data/config.yaml", "-r", "/bridges/signal.yaml"]
          volumeMounts:
            - name: data
              mountPath: /data
            - name: bridges
              mountPath: /bridges
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          {{- with .Values.bridges.signal.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      containers:
        - name: "bridge-signal"
          image: "{{ .Values.bridges.signal.image.repository }}:{{ .Values.bridges.signal.image.tag }}"
          imagePullPolicy: {{ .Values.bridges.signal.image.pullPolicy }}
          command: ["mautrix-signal"]
          args: ["-c", "/data/config.yaml"]
          ports:
            - name: bridge
              containerPort: 29318
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
            - name: signald
              mountPath: /signald
            - name: tmp
              mountPath: /tmp
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          {{- with .Values.bridges.signal.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "{{ include "matrix.fullname" . }}-signal-data"
        - name: signald
          persistentVolumeClaim:
            claimName: "{{ include "matrix.fullname" . }}-signald"
        - name: config
          configMap:
            name: "{{ include "matrix.fullname" . }}-signal-config"
        - name: bridges
          persistentVolumeClaim:
            claimName: "{{ include "matrix.fullname" . }}-bridges"
        - name: tmp
          emptyDir: {}
{{- end }}
